RC_ICONS = "Resources/MEM.ico"
VERSION = 417
MEM_YEAR = 2020
QMAKE_TARGET_COMPANY = MEM
QMAKE_TARGET_DESCRIPTION = Mass Effect Modder (MEM)
QMAKE_TARGET_COPYRIGHT = "Copyright 2014-$$MEM_YEAR Pawel Kolodziejski"
QMAKE_TARGET_PRODUCT = Mass Effect Modder
