RC_ICONS = "Resources/MEM.ico"
VERSION = 203
QMAKE_TARGET_COMPANY = MEM
QMAKE_TARGET_DESCRIPTION = Mass Effect Modder (MEM)
QMAKE_TARGET_COPYRIGHT = "Copyright 2014-2019 Pawel Kolodziejski"
QMAKE_TARGET_PRODUCT = Mass Effect Modder
